alias: "Good Morning Routine (Sleep Mode Ends)"
description: "Wake-up routine when Sleep Focus turns off"
mode: single

trigger:
  - platform: state
    entity_id: sensor.my_iphone_focus
    from: "sleep"
    to: "off"    # means no focus active

condition: []

action:
  # Fade in bedroom lights
  - service: light.turn_on
    target:
      entity_id: light.tradfri_bedroom
    data:
      brightness: 1

  - delay: "00:00:05"

  - service: light.turn_on
    target:
      entity_id: light.tradfri_bedroom
    data:
      brightness: 255
      transition: 900

  # Power on plugs
  - service: switch.turn_on
    target:
      entity_id:
        - switch.desk_plug

  # Wake-up WLED
  - service: light.turn_on
    target:
      entity_id: light.wled_desk
    data:
      brightness: 180
      effect: "Breathe"
      rgb_color: [255, 223, 100]
